#ifndef SC_LICENSE_H
#define SC_LICENSE_H
#include <stddef.h>

/*
 * License gate for the SCData native library. The public verification key is embedded at
 * build time (license_pubkey.h, generated by SCLicenseGenerator). A caller must present a
 * validly-signed license bound to its own package before any value method of the library
 * (encode/decode) will run.
 */

/* Result codes for sc_license_init. */
#define SC_LIC_OK              0
#define SC_LIC_ERR_MALFORMED  -1
#define SC_LIC_ERR_SIGNATURE  -2
#define SC_LIC_ERR_PACKAGE    -3
#define SC_LIC_ERR_NOT_YET    -4
#define SC_LIC_ERR_EXPIRED    -5

/*
 * Validates a license blob (the raw bytes of the .lic body, base64-decoded by the caller):
 *   - signature over the signed region using the embedded public key,
 *   - licensed package name == calling_package,
 *   - now within [validFrom, validTill]  (skipped when the no-date-check flag is set).
 * On success the library is marked licensed and returns SC_LIC_OK; otherwise a negative code.
 */
int sc_license_init(const unsigned char *lic, size_t lic_len, const char *calling_package);

/* 1 if a valid license was accepted by sc_license_init, else 0. Value methods gate on this. */
int sc_license_ok(void);

#endif
